### PR TITLE
feature/cmake facelift

### PR DESCRIPTION
**Pull request by bwpriest**
Modernized CMake somewhat to pull cereal headers directly so that the user no longer has to install them. Everything builds and all tests pass.

### CODE REVIEW

**Comment by steiltre** [comment]
This looks good. I have to learn more about how this works.

Can you remove the 'spack load cereal' lines from the .gitlab-ci.yml file as well to round out the way Cereal is included?

**Comment by bwpriest** [comment]
@steiltre I did the thing

**Comment by bwpriest** [comment]
I went ahead and rebased on top of the other PR to hopefully make things easier

**Comment by steiltre** [comment]
Thanks Ben!

**Pull request merged**
