### PR TITLE
v0.3 Release Prep

### PR DESCRIPTION
**Pull request by steiltre**

### CODE REVIEW

**Comment by steiltre** [comment]
Either one is fine with me. @bwpriest, do you want to put in the CMake change for v0.3, or wait until v0.4?

**Comment by bwpriest** [comment]
@steiltre I would like the cmake change to go in v0.3, as it will affect saltatlas and croquis. Can the release wait until next week?

**Comment by rogerpearce** [comment]
Ya, we can wait.

**Comment by steiltre** [comment]
@rogerpearce Anything else you want to sneak in before v0.3? The CMake changes, bugfix in the line_parser, and initial contributing.md are all in here.

**Pull request merged**
