### PR TITLE
Moved make_ygm_ptr to comm.

### PR DESCRIPTION
**Pull request by rogerpearce**
@steiltre Take a look at this one.

### CODE REVIEW

**Comment by rogerpearce** [comment]
@steiltre @bwpriest 

Take a look at this.   I think this is the last PR before making another release.

**Comment by bwpriest** [comment]
I should probably address Keita's cmake issue before we define a new release. I think that his proposed interface is smoother than what I did.

**Comment by rogerpearce** [comment]
> I should probably address Keita's cmake issue before we define a new release. I think that his proposed interface is smoother than what I did.

That's fine, we can hold off or that.   My next effort will be around mpi node layout, but will not put that in the next release.

**Comment by steiltre** [comment]
I'm good with this. I couldn't see any obvious ways this is broken.

**Pull request merged**
