### PR TITLE
Feature reduce by key

### PR DESCRIPTION
**Pull request by rogerpearce**
Added reduce_by_key_map and started new type traits features.

### CODE REVIEW

**Comment by rogerpearce** [comment]
@steiltre Look at the type_traits I added.   Should add support for knowing for_all_args.

**Comment by steiltre** [comment]
I also moved `include/ygm/container/reducing_adapter.hpp` to `include/ygm/container/detail/reducing_adapter.hpp` in my PR that got merged in yesterday, and yours is now overwriting mine.

Mind putting the `reducing_adapter.hpp` from `develop` in?

**Comment by steiltre** [comment]
I made a [PR](https://github.com/rogerpearce/ygm/pull/2) on your fork to address the clobbering of `reducing_adapter.hpp`.

Going to continue trying to understand the new black magic in your `ygm_traits.hpp`.

**Comment by steiltre** [comment]
`std::void_t` is pretty cool. Coming up with an easier way of doing this is worthwhile for maintainability, but this is a neat trick to avoid running into trouble calling `std::is_invocable` on a function that doesn't exist.

**Pull request merged**
