### PR TITLE
Adds missing include statements for new I/O functionality

### PR DESCRIPTION
**Pull request by steiltre**

### CODE REVIEW

**Comment by steiltre** [comment]
@rogerpearce Are there any implications for adding stdc++fs to target_link_libraries for the entire project? Or should we add this only where needed and require users to specify they need C++ filesystem support when linking?

**Comment by rogerpearce** [comment]
What compiler are you using?   This wasn't necessary for GCC9 or 10.    See the CI tests....

**Comment by steiltre** [comment]
I ran into this in GCC8. GCC9 removed the need for `-lstdc++fs`:
https://gcc.gnu.org/gcc-9/changes.html

**Comment by rogerpearce** [comment]
I vote we make GCC9 our minimum version.  OK?   @bwpriest ?

**Comment by bwpriest** [comment]
Fine by me

**Comment by rogerpearce** [comment]
Changed my mind.   If the current C++17 feature we are using are compiling with GCC8 we should support it.   I'll add a CI test for GCC8.

**Pull request merged**
