### PR TITLE
Modified ygm::container::array interface so that its lambda functions…

### PR DESCRIPTION
**Pull request by bwpriest**
… expect (std::pair<const index_type, value_type &>) instead of (index_type, value_type &).

### CODE REVIEW

**Comment by bwpriest** [comment]
@steiltre this does what I was asking for in issue #116, but it introduces a possible problem. I am packaging the index and value as a `std::pair<const index_type, value_type &>` so that the index type is const (similar to `std::map`), but using a `value_type &` or `value_type *` or `std::unique_ptr<value_type>` so that second type is modifiable appears to be necessary. However, this means that if we create a lambda with signature `[](const auto iv)`, then `iv.second` will still be modifiable in the body of the function even though the pair `iv` is declared const. I don't think that it will be possible to define remote or local lambdas that are guaranteed not to modify the array values, which could be a vector for bugs in downstream codes. Thoughts?

**Comment by bwpriest** [comment]
Also a bunch of the CI jobs failed for reasons that are not obvious to me. All tests pass locally. It looks like they are failing in different places also. I'm not sure what to make of that.

**Comment by steiltre** [comment]
Interesting. I played with this a little today, but I don't fully understand why a reference inside of a const pair ends up being modifiable. Is there a simple reason for this?

It looks like some of the CI jobs ran into issues downloading dependencies. Looks kind of like something happened on Microsoft's end. Everything passed when I re-ran.

**Comment by bwpriest** [comment]
> Interesting. I played with this a little today, but I don't fully understand why a reference inside of a const pair ends up being modifiable. Is there a simple reason for this?

I discovered that behavior accidentally, as I had also expected that the reference inside of the const pair would be const. It is also possible to modify the referenced object if the pair is passed by value. We might be able to store the pair as a `std::pair<const index_type, std::reference_wrapper<value_type>>`, but then we can no longer assign the value item using `=` so we lose the interoperability that I am trying to achieve with map lambdas. A final alternative might be creating a bespoke pair type with the behavior that we want, but that seems like it could be a problem long term.

I don't have a deep enough understanding of the language to make sense of why any of this is happening. 

> It looks like some of the CI jobs ran into issues downloading dependencies. Looks kind of like something happened on Microsoft's end. Everything passed when I re-ran.

Great, that's what I figured.

**Comment by bwpriest** [comment]
So what do we do about this? I'm worried about introducing such a potentially severe vector for bugs into the codebase, but this is the closest I was able to get to replicating the lambda interface of the map. Should we just discard this for now?

**Comment by steiltre** [comment]
I feel like there has to be some way around this. I want to take some more time to play with it. Definitely not worth discarding the effort. Uniformity of interfaces would be very nice.

**Comment by steiltre** [comment]
The most practical solution is probably to unify interfaces by leaving the `ygm::container::array` as it is and splitting apart the `std::pair<key, value>` used in the lambdas for `ygm::container::map`. This choice was made to conform to the interface for `std::map`, but this isn't of great value. Roger pointed out that we may run into similar issues as we start rolling our own hash tables.

**Comment by bwpriest** [comment]
> The most practical solution is probably to unify interfaces by leaving the `ygm::container::array` as it is and splitting apart the `std::pair<key, value>` used in the lambdas for `ygm::container::map`. This choice was made to conform to the interface for `std::map`, but this isn't of great value. Roger pointed out that we may run into similar issues as we start rolling our own hash tables.

I also considered this, but adopting this strategy will also mean that we cannot use the same lambdas with `ygm::container::bag` with `std::pair` template types. We would need a separate `pair_bag` type that also splits the pair into separate arguments. That would not be the end of the world, but it is something to consider.

They said, there might be some magic we can do to automatically split pairs and tuples up into variadic arguments.

**Comment by bwpriest** [comment]
> The most practical solution is probably to unify interfaces by leaving the `ygm::container::array` as it is and splitting apart the `std::pair<key, value>` used in the lambdas for `ygm::container::map`. This choice was made to conform to the interface for `std::map`, but this isn't of great value. Roger pointed out that we may run into similar issues as we start rolling our own hash tables.

@steiltre do you want me to abandon this PR and work on one that does the opposite, as you described here?

**Comment by steiltre** [comment]
> > The most practical solution is probably to unify interfaces by leaving the `ygm::container::array` as it is and splitting apart the `std::pair<key, value>` used in the lambdas for `ygm::container::map`. This choice was made to conform to the interface for `std::map`, but this isn't of great value. Roger pointed out that we may run into similar issues as we start rolling our own hash tables.
> 
> I also considered this, but adopting this strategy will also mean that we cannot use the same lambdas with `ygm::container::bag` with `std::pair` template types. We would need a separate `pair_bag` type that also splits the pair into separate arguments. That would not be the end of the world, but it is something to consider.
> 
> They said, there might be some magic we can do to automatically split pairs and tuples up into variadic arguments.

I hadn't thought about that use case. Splitting pairs seems like an easier problem to tackle. A bit of `std::is_invocable` may allow the case of bags to be interacted with in both ways.

**Comment by steiltre** [comment]
> @steiltre do you want me to abandon this PR and work on one that does the opposite, as you described here?

That's my vote. You're the only one this change immediately affects though, so I have no problem if you want to take some time and consider the options more.

**Comment by bwpriest** [comment]
> > @steiltre do you want me to abandon this PR and work on one that does the opposite, as you described here?
> 
> That's my vote. You're the only one this change immediately affects though, so I have no problem if you want to take some time and consider the options more.

Ok I'm going to abandon this branch and work on the splitting the map lambdas to expect separate key and value types

**Pull request closed without merging**
