### PR TITLE
ygm::comm::Layout class

### PR DESCRIPTION
**Pull request by bwpriest**
Right now, ygm::comm::layout() turns a const reference to an instance of the ygm::Layout class. I tried to instead keep a const public ygm::Layout member in ygm::comm, but the comm/comm_impl pattern made that difficult.

### CODE REVIEW

**Comment by bwpriest** [comment]
We should revisit nomenclature before merging, decide whether to remove ygm::comm::rank() and ygm::comm::size() in favor of ygm::Layout::rank() and ygm::Layout::count(), and determine whether to hang onto the local and node communicators we create while constructing ygm::Layout.

**Comment by bwpriest** [comment]
This is ready now. I also added the `ygm::Layout::local_ranks()` and `ygm::Layout::strided_ranks()` functions that were missing before, as well as a `ygm::Layout::is_strided()` function analogous to `ygm::Layout::is_local()`. Note that currently `ygm::Layout::nl_to_rank()` assumes that `rank = node_id * local_size + local_id`, which is implementation dependent and thus could be wrong depending on the linked version of MPI.

**Comment by rogerpearce** [comment]
Just noticed the capital L -- all other classes in YGM are lowercae, lets stick to snake case.

**Comment by bwpriest** [comment]
I initially tried to name it `ygm::layout`, but that collided with the `ygm::comm::layout()` function name. Should I hide it behind a namespace such as `ygm::detail::layout`?

**Comment by rogerpearce** [comment]
ygm::detail::layout is great.

**Comment by bwpriest** [comment]
I just noticed that adding the layout makes `test_comm_2.cpp` a lot slower (now takes ~45s on quartz) due to the new allgathers used while constructing the `ygm::detail::layout` members. Is this a problem?

**Comment by steiltre** [comment]
Hitting all of those destructors in `test_comm_2` is pretty expensive. Each one involves an `MPI_Barrier` and a `ygm::comm::barrier()` (which has a loop calling `MPI_Iallreduce`).

**Pull request merged**
